[target.aarch64-unknown-linux-gnu]
image="prog-vb/aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image="prog-vb/armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-linux-gnu]
image="prog-vb/x86_64-unknown-linux-gnu"
